In [ ]:
import pandas as pd
import os

# List of filenames
file_names = [
    'combined_bundles.curves.whole.vertex.harm.map_AD.csv',
    'combined_bundles.curves.whole.vertex.harm.map_FA.csv',
    'combined_bundles.curves.whole.vertex.harm.map_MD.csv',
    'combined_bundles.curves.whole.vertex.harm.map_RD.csv',
    'combined_bundles.curves.whole.voxel.harm.map_AD.csv',
    'combined_bundles.curves.whole.voxel.harm.map_FA.csv',
    'combined_bundles.curves.whole.voxel.harm.map_MD.csv',
    'combined_bundles.curves.whole.voxel.harm.map_RD.csv',
    'combined_bundles.tissue.whole.vertex.harm.map_AD.csv',
    'combined_bundles.tissue.whole.vertex.harm.map_FA.csv',
    'combined_bundles.tissue.whole.vertex.harm.map_MD.csv',
    'combined_bundles.tissue.whole.vertex.harm.map_RD.csv',
    'combined_bundles.tissue.whole.voxel.harm.map_AD.csv',
    'combined_bundles.tissue.whole.voxel.harm.map_FA.csv',
    'combined_bundles.tissue.whole.voxel.harm.map_MD.csv',
    'combined_bundles.tissue.whole.voxel.harm.map_RD.csv'
]

# Path where the data files are saved
base_path = '/content/'

# Dictionary to store the datasets
datasets = {}

# Load each file and store it in the datasets dictionary
for file in file_names:
    file_path = os.path.join(base_path, file)
    data = pd.read_csv(file_path)
    datasets[file] = data

# Check the first few rows of a dataset to ensure it loaded correctly
print(datasets['combined_bundles.curves.whole.vertex.harm.map_AD.csv'].head())


     id      tp site  fimbria_left  vofb_left  slfc_right  ifof_right  \
0  1008  day030  UEF      1.233815   1.044077    1.066871    1.094711   
1  1008  day150  UEF           NaN   1.225394    1.030815    1.085285   
2  1008  day002  UEF      1.139111   1.075247    1.081033    1.096676   
3  1008  day009  UEF      1.197886   0.964140    1.064728    1.090127   
4  1012  day002  UEF      1.335006   1.080414    1.094223    1.099709   

     cc_ant  cerped_left  slfb_left  ...  slfd_left  slfc_left  opticrad_left  \
0  1.196576     1.046947   0.990959  ...        NaN   1.060020            NaN   
1  1.207856     1.101025   1.048995  ...        NaN   1.091164            NaN   
2  1.194813     1.074878   0.993329  ...        NaN        NaN            NaN   
3  1.204621     1.068170   0.998651  ...        NaN   1.023920       0.955890   
4  1.216506     1.053619   1.010615  ...        NaN   1.095982       1.068405   

   chip_left  amyhypdor_left  cc_mid  vofa_left   cc_temp  amyhypdor_right

In [ ]:
import numpy as np

# Define the columns to remove
columns_to_remove = [
    "amyhypven_right", "amyhypven_left", "cerped_left", "cerped_right",
    "opticrad_right", "vofb_right", "vofa_right", "ifof_left", "ifof_right",
    "ilf_left", "ilf_right", "slfa_left", "slfa_right", "slfb_left", "slfb_right",
    "slfc_left", "slfc_right"
]

# Time point renaming
tp_mapping = {
    "day002": "2d",
    "day009": "9d",
    "day030": "1mo",
    "day150": "5mo"
}

for file_name, data in datasets.items():
    # Filter out 'Sham'
    data = data[data['outcome'] != 'Sham']

    # Rename time points
    data['tp'] = data['tp'].replace(tp_mapping)

    # Drop unnecessary columns
    data = data.drop(columns=columns_to_remove, errors='ignore')

    # Impute missing values with the mean for numeric columns
    data.fillna(data.mean(numeric_only=True), inplace=True)

    # Store the processed dataset back in the dictionary
    datasets[file_name] = data

# Check the processed data for one of the files
print(datasets['combined_bundles.curves.whole.vertex.harm.map_AD.csv'].head())


<ipython-input-2-98d6ee42e8f0>:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tp'] = data['tp'].replace(tp_mapping)
<ipython-input-2-98d6ee42e8f0>:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tp'] = data['tp'].replace(tp_mapping)
<ipython-input-2-98d6ee42e8f0>:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/st

     id   tp site  fimbria_left  vofb_left    cc_ant  thalslat_right  \
0  1008  1mo  UEF      1.233815   1.044077  1.196576        1.008876   
1  1008  5mo  UEF      1.255606   1.225394  1.207856        0.975094   
2  1008   2d  UEF      1.139111   1.075247  1.194813        0.976676   
3  1008   9d  UEF      1.197886   0.964140  1.204621        1.029332   
4  1012   2d  UEF      1.335006   1.080414  1.216506        1.047818   

   cing_right  thalsub_right  cing_left  ...  ant_comm  slfd_left  \
0    1.099840       1.052048   1.071958  ...  1.126810     0.9948   
1    1.072898       1.080886   1.088939  ...  1.101498     0.9948   
2    1.132900       1.112699   1.061460  ...  1.126517     0.9948   
3    1.082552       1.079167   1.046353  ...  1.130959     0.9948   
4    1.157954       1.122634   1.112285  ...  1.144419     0.9948   

   opticrad_left  chip_left  amyhypdor_left    cc_mid  vofa_left   cc_temp  \
0       1.042356   1.141278        1.222997  1.200988   1.017445  1.230661

<ipython-input-2-98d6ee42e8f0>:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tp'] = data['tp'].replace(tp_mapping)


In [ ]:
import numpy as np

columns_to_remove = [
    "amyhypven_right", "amyhypven_left", "cerped_left", "cerped_right",
    "opticrad_right", "vofb_right", "vofa_right", "ifof_left", "ifof_right",
    "ilf_left", "ilf_right", "slfa_left", "slfa_right", "slfb_left", "slfb_right",
    "slfc_left", "slfc_right"
]

tp_mapping = {
    "day002": "2d",
    "day009": "9d",
    "day030": "1mo",
    "day150": "5mo"
}

for file_name, data in datasets.items():
    data = data[data['outcome'] != 'Sham'].copy()

    data.loc[:, 'tp'] = data['tp'].replace(tp_mapping)

    data = data.drop(columns=columns_to_remove, errors='ignore')

    data.fillna(data.mean(numeric_only=True), inplace=True)

    datasets[file_name] = data

print(datasets['combined_bundles.curves.whole.vertex.harm.map_AD.csv'].head())


     id   tp site  fimbria_left  vofb_left    cc_ant  thalslat_right  \
0  1008  1mo  UEF      1.233815   1.044077  1.196576        1.008876   
1  1008  5mo  UEF      1.255606   1.225394  1.207856        0.975094   
2  1008   2d  UEF      1.139111   1.075247  1.194813        0.976676   
3  1008   9d  UEF      1.197886   0.964140  1.204621        1.029332   
4  1012   2d  UEF      1.335006   1.080414  1.216506        1.047818   

   cing_right  thalsub_right  cing_left  ...  ant_comm  slfd_left  \
0    1.099840       1.052048   1.071958  ...  1.126810     0.9948   
1    1.072898       1.080886   1.088939  ...  1.101498     0.9948   
2    1.132900       1.112699   1.061460  ...  1.126517     0.9948   
3    1.082552       1.079167   1.046353  ...  1.130959     0.9948   
4    1.157954       1.122634   1.112285  ...  1.144419     0.9948   

   opticrad_left  chip_left  amyhypdor_left    cc_mid  vofa_left   cc_temp  \
0       1.042356   1.141278        1.222997  1.200988   1.017445  1.230661

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import os

model_save_path = '/content/saved_models/'
os.makedirs(model_save_path, exist_ok=True)


models = {
    'SVM': SVC(class_weight='balanced', probability=True),
    'LogisticRegression': LogisticRegression(class_weight='balanced', max_iter=1000),
    'RandomForest': RandomForestClassifier(class_weight='balanced')
}


meta_fields = ["id", "tp", "site", "outcome"]


for file_name, data in datasets.items():
    print(f"Running models for dataset: {file_name}")


    metrics = data.columns.difference(meta_fields)


    for time_point in data['tp'].unique():
        print(f"Processing time point: {time_point}")


        df = data[data['tp'] == time_point]

        X = df[metrics]
        y = df['outcome']

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        for model_name, model in models.items():
            print(f"Training {model_name}...")
            model.fit(X_train, y_train)

            y_pred = model.predict(X_test)

            conf_matrix = confusion_matrix(y_test, y_pred)
            class_report = classification_report(y_test, y_pred)

            save_file_path = os.path.join(model_save_path, f"{model_name}_{file_name}_{time_point}.txt")
            with open(save_file_path, 'w') as f:
                f.write(f"Model: {model_name}\n")
                f.write(f"Time Point: {time_point}\n")
                f.write("\nConfusion Matrix:\n")
                f.write(str(conf_matrix) + "\n")
                f.write("\nClassification Report:\n")
                f.write(class_report + "\n")

            print(f"{model_name} results saved for {file_name} at {time_point}")


            print(f"{model_name} for {file_name} at {time_point}")
            print("\nConfusion Matrix:\n")
            print(conf_matrix)
            print("\nClassification Report:\n")
            print(class_report)


Running models for dataset: combined_bundles.curves.whole.vertex.harm.map_AD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
SVM for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo

Confusion Matrix:

[[ 3  2]
 [11  1]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.21      0.60      0.32         5
         TBI       0.33      0.08      0.13        12

    accuracy                           0.24        17
   macro avg       0.27      0.34      0.22        17
weighted avg       0.30      0.24      0.19        17

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
LogisticRegression for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo

Confusion Matrix:

[[2 3]
 [6 6]]

Classification Report:

              precision    recall  f1-score   support

         

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 5mo
SVM for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 5mo

Confusion Matrix:

[[2 3]
 [6 4]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.25      0.40      0.31         5
         TBI       0.57      0.40      0.47        10

    accuracy            

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 2d
RandomForest for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 2d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Processing time point: 9d
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 9d
SVM for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 9d

Confusion Matrix:

[[ 2  1]
 [10  4]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.17      0.67      0.27         3
         TBI       0.80      0.29      0.42        14

    accuracy             

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 1mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 5mo
SVM for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 5mo

Confusion Matrix:

[[2 3]
 [7 3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.22      0.40      0.29         5
         TBI       0.50      0.30      0.38        10

    accuracy            

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 5mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 2d
SVM for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 2d

Confusion Matrix:

[[0 3]
 [8 6]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.67      0.43      0.52        14

    accuracy               

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 2d
RandomForest for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 2d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Processing time point: 9d
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 9d
SVM for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 2  1]
 [13  1]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.13      0.67      0.22         3
         TBI       0.50      0.07      0.12        14

    accuracy             

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 9d
RandomForest for combined_bundles.curves.whole.vertex.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Running models for dataset: combined_bundles.curves.whole.vertex.harm.map_MD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 1mo
SVM for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 1mo

Confusion Matrix:

[[4 1]
 [9 3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.31      0.80      0.44         5


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 1mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 5mo
SVM for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 5mo

Confusion Matrix:

[[ 1  4]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       1.00      0.20      0.33         5
         TBI       0.71      1.00      0.83        10

    accuracy        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 5mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 2d
SVM for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 2d

Confusion Matrix:

[[ 0  3]
 [10  4]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.57      0.29      0.38        14

    accuracy           

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 9d
RandomForest for combined_bundles.curves.whole.vertex.harm.map_MD.csv at 9d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Running models for dataset: combined_bundles.curves.whole.vertex.harm.map_RD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 1mo
SVM for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 1mo

Confusion Matrix:

[[1 4]
 [9 3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.10      0.20      0.13         5


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 1mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 5mo
SVM for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 5mo

Confusion Matrix:

[[ 1  4]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       1.00      0.20      0.33         5
         TBI       0.71      1.00      0.83        10

    accuracy        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 2d
RandomForest for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 2d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Processing time point: 9d
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 9d
SVM for combined_bundles.curves.whole.vertex.harm.map_RD.csv at 9d

Confusion Matrix:

[[2 1]
 [8 6]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.20      0.67      0.31         3
         TBI       0.86      0.43      0.57        14

    accuracy                 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 1mo
RandomForest for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 5mo
SVM for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 5mo

Confusion Matrix:

[[1 4]
 [2 8]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.33      0.20      0.25         5
         TBI       0.67      0.80      0.73        10

    accuracy                

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 5mo
RandomForest for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 2d
SVM for combined_bundles.curves.whole.voxel.harm.map_AD.csv at 2d

Confusion Matrix:

[[ 1  2]
 [11  3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.08      0.33      0.13         3
         TBI       0.60      0.21      0.32        14

    accuracy               

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 1mo
SVM for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 1mo

Confusion Matrix:

[[ 4  1]
 [11  1]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.27      0.80      0.40         5
         TBI       0.50      0.08      0.14        12

    accuracy                           0.29        17
   macro avg       0.38      0.44      0.27        17
weighted avg       0.43      0.29      0.22        17

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 1mo
LogisticRegression for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 1mo

Confusion Matrix:

[[0 5]
 [6 6]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.55      0.50      0

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


SVM results saved for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 9d
SVM for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 3  0]
 [12  2]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.20      1.00      0.33         3
         TBI       1.00      0.14      0.25        14

    accuracy                           0.29        17
   macro avg       0.60      0.57      0.29        17
weighted avg       0.86      0.29      0.26        17

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 9d
LogisticRegression for combined_bundles.curves.whole.voxel.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 0  3]
 [11  3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.50      0.21      0.30        14

    accuracy                

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


SVM results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 1mo
SVM for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 1mo

Confusion Matrix:

[[4 1]
 [8 4]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.33      0.80      0.47         5
         TBI       0.80      0.33      0.47        12

    accuracy                           0.47        17
   macro avg       0.57      0.57      0.47        17
weighted avg       0.66      0.47      0.47        17

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 1mo
LogisticRegression for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 1mo

Confusion Matrix:

[[4 1]
 [4 8]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.50      0.80      0.62         5
         TBI       0.89      0.67      0.76        12

    accuracy                    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


SVM results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 5mo
SVM for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 5mo

Confusion Matrix:

[[ 1  4]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       1.00      0.20      0.33         5
         TBI       0.71      1.00      0.83        10

    accuracy                           0.73        15
   macro avg       0.86      0.60      0.58        15
weighted avg       0.81      0.73      0.67        15

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 5mo
LogisticRegression for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 5mo

Confusion Matrix:

[[1 4]
 [4 6]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.20      0.20      0.20         5
         TBI       0.60      0.60      0.60        10

    accuracy                

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


SVM results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 2d
SVM for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 2d

Confusion Matrix:

[[ 1  2]
 [11  3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.08      0.33      0.13         3
         TBI       0.60      0.21      0.32        14

    accuracy                           0.24        17
   macro avg       0.34      0.27      0.22        17
weighted avg       0.51      0.24      0.28        17

Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 2d
LogisticRegression for combined_bundles.curves.whole.voxel.harm.map_MD.csv at 2d

Confusion Matrix:

[[0 3]
 [9 5]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.62      0.36      0.45        14

    accuracy                    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


LogisticRegression results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 1mo
LogisticRegression for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 1mo

Confusion Matrix:

[[1 4]
 [8 4]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.11      0.20      0.14         5
         TBI       0.50      0.33      0.40        12

    accuracy                           0.29        17
   macro avg       0.31      0.27      0.27        17
weighted avg       0.39      0.29      0.32        17

Training RandomForest...
RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 1mo
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 1 11]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.69      0.92      0.79        12

    accuracy

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 5mo
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 2d
SVM for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 2d

Confusion Matrix:

[[0 3]
 [6 8]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.73      0.57      0.64        14

    accuracy               

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 2d
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 2d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Processing time point: 9d
Training SVM...
SVM results saved for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 9d
SVM for combined_bundles.tissue.whole.vertex.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 1  2]
 [11  3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.08      0.33      0.13         3
         TBI       0.60      0.21      0.32        14

    accuracy             

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 1mo
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 5mo
SVM for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 5mo

Confusion Matrix:

[[ 1  4]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       1.00      0.20      0.33         5
         TBI       0.71      1.00      0.83        10

    accuracy        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 5mo
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 2d
SVM for combined_bundles.tissue.whole.vertex.harm.map_MD.csv at 2d

Confusion Matrix:

[[ 0  3]
 [11  3]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.50      0.21      0.30        14

    accuracy           

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.vertex.harm.map_RD.csv at 1mo
RandomForest for combined_bundles.tissue.whole.vertex.harm.map_RD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.vertex.harm.map_RD.csv at 5mo
SVM for combined_bundles.tissue.whole.vertex.harm.map_RD.csv at 5mo

Confusion Matrix:

[[1 4]
 [1 9]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.50      0.20      0.29         5
         TBI       0.69      0.90      0.78        10

    accuracy            

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_AD.csv at 1mo
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_AD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_AD.csv at 5mo
SVM for combined_bundles.tissue.whole.voxel.harm.map_AD.csv at 5mo

Confusion Matrix:

[[1 4]
 [8 2]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.11      0.20      0.14         5
         TBI       0.33      0.20      0.25        10

    accuracy                

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 5mo
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 5mo

Confusion Matrix:

[[ 0  5]
 [ 0 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.67      1.00      0.80        10

    accuracy                           0.67        15
   macro avg       0.33      0.50      0.40        15
weighted avg       0.44      0.67      0.53        15

Processing time point: 2d
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 2d
SVM for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 2d

Confusion Matrix:

[[1 2]
 [7 7]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.12      0.33      0.18         3
         TBI       0.78      0.50      0.61        14

    accuracy                   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 2d
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 2d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Processing time point: 9d
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 9d
SVM for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 3  0]
 [12  2]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.20      1.00      0.33         3
         TBI       1.00      0.14      0.25        14

    accuracy                 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 9d
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_FA.csv at 9d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Running models for dataset: combined_bundles.tissue.whole.voxel.harm.map_MD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_MD.csv at 1mo
SVM for combined_bundles.tissue.whole.voxel.harm.map_MD.csv at 1mo

Confusion Matrix:

[[ 4  1]
 [11  1]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.27      0.80      0.40         5
 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_MD.csv at 9d
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_MD.csv at 9d

Confusion Matrix:

[[ 0  3]
 [ 0 14]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         3
         TBI       0.82      1.00      0.90        14

    accuracy                           0.82        17
   macro avg       0.41      0.50      0.45        17
weighted avg       0.68      0.82      0.74        17

Running models for dataset: combined_bundles.tissue.whole.voxel.harm.map_RD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 1mo
SVM for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 1mo

Confusion Matrix:

[[ 1  4]
 [ 2 10]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.33      0.20      0.25         5
 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


RandomForest results saved for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 1mo
RandomForest for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 1mo

Confusion Matrix:

[[ 0  5]
 [ 0 12]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.00      0.00      0.00         5
         TBI       0.71      1.00      0.83        12

    accuracy                           0.71        17
   macro avg       0.35      0.50      0.41        17
weighted avg       0.50      0.71      0.58        17

Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 5mo
SVM for combined_bundles.tissue.whole.voxel.harm.map_RD.csv at 5mo

Confusion Matrix:

[[1 4]
 [3 7]]

Classification Report:

              precision    recall  f1-score   support

         PTE       0.25      0.20      0.22         5
         TBI       0.64      0.70      0.67        10

    accuracy                

In [ ]:

from sklearn.metrics import balanced_accuracy_score

model_save_path = '/content/saved_models/'
os.makedirs(model_save_path, exist_ok=True)

models = {
    'SVM': SVC(class_weight='balanced', probability=True),
    'LogisticRegression': LogisticRegression(class_weight='balanced', max_iter=1000),
    'RandomForest': RandomForestClassifier(class_weight='balanced')
}


meta_fields = ["id", "tp", "site", "outcome"]


for file_name, data in datasets.items():
    print(f"Running models for dataset: {file_name}")


    metrics = data.columns.difference(meta_fields)


    for time_point in data['tp'].unique():
        print(f"Processing time point: {time_point}")


        df = data[data['tp'] == time_point]

        X = df[metrics]
        y = df['outcome']

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        for model_name, model in models.items():
            print(f"Training {model_name}...")
            model.fit(X_train, y_train)

            y_pred = model.predict(X_test)

            balanced_acc = balanced_accuracy_score(y_test, y_pred)

            save_file_path = os.path.join(model_save_path, f"{model_name}_{file_name}_{time_point}.txt")
            with open(save_file_path, 'w') as f:
                f.write(f"Model: {model_name}\n")
                f.write(f"Time Point: {time_point}\n")
                f.write(f"Balanced Accuracy: {balanced_acc}\n")

            print(f"{model_name} results saved for {file_name} at {time_point}")

            print(f"{model_name} for {file_name} at {time_point}")
            print(f"Balanced Accuracy: {balanced_acc}")


Running models for dataset: combined_bundles.curves.whole.vertex.harm.map_AD.csv
Processing time point: 1mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
SVM for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
Balanced Accuracy: 0.3416666666666667
Training LogisticRegression...
LogisticRegression results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
LogisticRegression for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
Balanced Accuracy: 0.45
Training RandomForest...
RandomForest results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
RandomForest for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 1mo
Balanced Accuracy: 0.4583333333333333
Processing time point: 5mo
Training SVM...
SVM results saved for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 5mo
SVM for combined_bundles.curves.whole.vertex.harm.map_AD.csv at 5mo
Balanced Accuracy: 0.4
Traini

In [ ]:

import os

model_save_path = '/content/saved_models/'
results = {}

for filename in os.listdir(model_save_path):
    if filename.endswith(".txt"):
        file_path = os.path.join(model_save_path, filename)
        with open(file_path, 'r') as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("Balanced Accuracy:"):
                    balanced_accuracy = float(line.split(":")[1].strip())
                    results[filename] = balanced_accuracy

if results:
    best_model_filename = max(results, key=results.get)
    best_balanced_accuracy = results[best_model_filename]
    print(f"The model with the highest balanced accuracy is: {best_model_filename}")
    print(f"Balanced Accuracy: {best_balanced_accuracy}")
else:
    print("No results found in the saved models directory.")


The model with the highest balanced accuracy is: LogisticRegression_combined_bundles.curves.whole.vertex.harm.map_MD.csv_9d.txt
Balanced Accuracy: 0.75
